### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by digitalhobo** [twohyjr/2etime-Graphics#1]
Hi - thanks for the great tutorials on youtube. And for sharing the code.
Is it possible you could share the Assets directory in your source code, it seems to be missing in the xcode project.

:0)

**Comment by twohyjr** [comment]
Ya man of course. I am not near my computer right now but I will in the morning.   Pretty soon I will be doing another tutorial series, with shorter vids for different categories and more in depth explanations. It will basically be the same stuff only more thought out in advance.  Just a heads up.

**Comment by twohyjr** [comment]
Updated Assets Folder

**Comment by digitalhobo** [comment]
Thank You :0)
